spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matchbell?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: match_user
    password: match_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "fkashfeuhfihnkvbFJHhUJBFUHIR937474HSDGFUI3R"

  # Access Token 만료 시간 (초) – 1시간
  access-expiration-seconds: 3600

  # Refresh Token 만료 시간 (초) – 14일 (3600 * 24 * 14)
  refresh-expiration-seconds: 1209600


saju:
  python:
    # （/opt/saju/venv/bin/python）
    executable: /opt/saju/venv/bin/python
    # （/opt/saju/saju_cli.py）
    script-path: /opt/saju/saju_cli.py

file:
  # 서버에 업로드된 프로필 사진 저장 경로
  upload-dir: /opt/app/uploads/profile
